version: 2.1

jobs:
  mybuildjob:
    docker:
      - image: docker/compose:1.29.1
    steps:
      - checkout
      - run:
          name: build and push
          command: |
             docker-compose -f docker-compose.build.yaml build --parallel
             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
             docker push binay18shah/udagram-api-feed
             docker push binay18shah/udagram-api-user
             docker push binay18shah/udagram-frontend
             docker push binay18shah/reverseproxy

worksflows: 
  version: 2  
  jobs:
    - mybuildjob
    environment:
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD

  
    
        
