version: 2.1
jobs:
  build:    
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Check versions
          command: |
            docker --version
            docker-compose --version
      - run:
          name: Build images
          command: |                 
            docker build /udagram-api-feed -t udagram-api-feed
            docker build /udagram-api-user -t udagram-api-user
            docker build /udagram-frontend -t udagram-frontend
            docker build /udagram-reverseproxy -t reverseproxy
            
      - run:
          name: Push images
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push binay18shah/udagram-frontend
            docker push binay18shah/udagram-api-feed
            docker push binay18shah/udagram-api-user
            docker push binay18shah/udagram-reverseproxy
    environment:
      DOCKER_USERNAME: "$DOCKER_USERNAME"
      DOCKER_PASSWORD: "$DOCKER_PASSWORD"