version: 2.1
jobs:
  build:    
    working_directory: ~/cd0354-monolith-to-microservices-project
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check versions
          command: |
            docker --version
            docker-compose --version
      - run:
          name: Build images
          command: |                 
            docker build -t udagram-api-feed udagram-api-feed
            docker build -t udagram-api-user udagram-api-user 
            docker build -t udagram-frontend udagram-frontend 
            docker build -t reverseproxy udagram-reverseproxy 
            
      - run:
          name: Push images
          command: |
            echo "$DOCKER_PASSWORD" | docker login hub.docker.com -u "$DOCKER_USERNAME" --password-stdin
            docker push binay18shah/udagram-frontend
            docker push binay18shah/udagram-api-feed
            docker push binay18shah/udagram-api-user
            docker push binay18shah/udagram-reverseproxy
    environment:
      DOCKER_USERNAME: "$DOCKER_USERNAME"
      DOCKER_PASSWORD: "$DOCKER_PASSWORD"