version: 2.1

jobs:
  mybuildjob:
    docker:
      - image: docker/compose:1.29.1
    steps:
      - checkout
      - run:
          name: build and push
          command: |
             docker-compose -f docker-compose-build.yaml build --parallel
             echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
             docker push binay18shah/udagram-api-feed:v1
             docker push binay18shah/udagram-api-user:v1
             docker push binay18shah/udagram-frontend:v1
             docker push binay18shah/reverseproxy:v1

workflows: 
  version: 2  
  build_and_push:
    jobs:
      - mybuildjob
      

  
    
        
